<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>InventoryPOS</AssemblyTitle>
    <AssemblyDescription>Clothing inventory management for resale</AssemblyDescription>
    <AssemblyProduct>InventoryPOS</AssemblyProduct>
    <Version>1.5.2</Version>
    <FileVersion>1.5.2</FileVersion>
    <InformationalVersion>1.5.2</InformationalVersion>
      </PropertyGroup>

</Project>